---
os: linux
dist: bionic
language: python

_backend_build: &backend_build
  before_install:
    - pip install poetry
  install:
    - poetry install -vv
  script:
    - poetry run flake8
    - poetry run black --check .
    - poetry run pyre --noninteractive
    - poetry run green --run-coverage

_frontend_build: &frontend_build
  before_install:
    - cd frontend/
  install:
    - yarn install
  script:
    - yarn lint
    - yarn run prettier --check src/
    - yarn run tsc
    - yarn build
    - yarn test --coverage --collectCoverageFrom "src/**/*"

jobs:
  include:
    - language: python
      python: "3.7"
      <<: *backend_build
    - language: python
      python: "3.8"
      <<: *backend_build
    - language: node_js
      node_js: "14"
      <<: *frontend_build

after_success:
  - pip install codecov
  - codecov
