---
name: CI

# yamllint disable-line rule:truthy
on: [push]

jobs:
  setup-venv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: syphar/restore-virtualenv@v1
        id: venv-cache
      - uses: abatilo/actions-poetry@v2.1.0
        if: steps.setup-venv.outputs.cache-hit != 'true'
      - name: Install Python dependencies
        run: poetry install -vv
        if: steps.setup-venv.outputs.cache-hit != 'true'

  backend-build:
    runs-on: ubuntu-latest
    needs: setup-venv
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: syphar/restore-virtualenv@v1
        id: venv-cache
      - run: poetry run flake8
      - run: poetry run black --check .
      - run: poetry run pyre --noninteractive
      - run: poetry run green --run-coverage
      - run: poetry run coverage xml
      - uses: actions/upload-artifact@v2
        with:
          name: backend-coverage
          path: coverage.xml

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn lint
      - run: yarn run prettier --check src/
      - run: yarn run tsc
      - run: yarn build
      - run: yarn test --coverage --collectCoverageFrom "src/**/*"
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-coverage
          path: frontend/coverage/coverage-final.json

  codecov:
    runs-on: ubuntu-latest
    needs: [backend-build, frontend-build]
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve backend test coverage
        uses: actions/download-artifact@v2
        with:
          name: backend-coverage
          path: backend-coverage.xml
      - name: Retrieve frontend test coverage
        uses: actions/download-artifact@v2
        with:
          name: frontend-coverage
          path: frontend-coverage.json
      - uses: codecov/codecov-action@v1
        with:
          files: ./backend-coverage.xml,./frontend-coverage.json
