---
name: CI

# yamllint disable-line rule:truthy
on: [push]

jobs:
  setup-venv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: syphar/restore-virtualenv@v1
        id: venv-cache
      - uses: abatilo/actions-poetry@v2.1.0
        if: steps.setup-venv.outputs.cache-hit != 'true'
      - name: Install Python dependencies
        run: poetry install -vv
        if: steps.setup-venv.outputs.cache-hit != 'true'

  backend-build:
    runs-on: ubuntu-latest
    needs: setup-venv
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: syphar/restore-virtualenv@v1
        id: venv-cache
      - name: flake8
        run: poetry run flake8
      - name: black
        run: poetry run black --check .
      - name: pyre
        run: poetry run pyre --noninteractive
      - name: green
        run: poetry run green --run-coverage

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: prettier --check src/
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run tsc
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test --coverage --collectCoverageFrom "src/**/*"
